/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/home/scutech/Desktop/my/vuepress-blog/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0d1153ac",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d1153ac").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-620c8935",
    path: "/blog/tool/VScode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-620c8935").then(next)
    },
  },
  {
    name: "v-815124bc",
    path: "/blog/tool/node%E5%92%8Cnpm.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-815124bc").then(next)
    },
  },
  {
    path: "/blog/tool/node和npm.html",
    redirect: "/blog/tool/node%E5%92%8Cnpm.html"
  },
  {
    name: "v-0d827ab0",
    path: "/blog/tool/%E5%B8%B8%E7%94%A8%E5%B7%A5%E5%85%B7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d827ab0").then(next)
    },
  },
  {
    path: "/blog/tool/常用工具.html",
    redirect: "/blog/tool/%E5%B8%B8%E7%94%A8%E5%B7%A5%E5%85%B7.html"
  },
  {
    name: "v-67b6f28f",
    path: "/blog/web/PC%E3%80%81%E7%A7%BB%E5%8A%A8%E7%AB%AF%E6%8B%96%E6%8B%BD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67b6f28f").then(next)
    },
  },
  {
    path: "/blog/web/PC、移动端拖拽.html",
    redirect: "/blog/web/PC%E3%80%81%E7%A7%BB%E5%8A%A8%E7%AB%AF%E6%8B%96%E6%8B%BD.html"
  },
  {
    name: "v-407b253a",
    path: "/blog/web/VuePress%20%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E5%A1%AB%E5%9D%91.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-407b253a").then(next)
    },
  },
  {
    path: "/blog/web/VuePress 个人博客填坑.html",
    redirect: "/blog/web/VuePress%20%E4%B8%AA%E4%BA%BA%E5%8D%9A%E5%AE%A2%E5%A1%AB%E5%9D%91.html"
  },
  {
    name: "v-63a7a701",
    path: "/blog/web/babel7%E9%85%8D%E7%BD%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63a7a701").then(next)
    },
  },
  {
    path: "/blog/web/babel7配置.html",
    redirect: "/blog/web/babel7%E9%85%8D%E7%BD%AE.html"
  },
  {
    name: "v-d839e64a",
    path: "/blog/web/canvas%E4%BF%9D%E5%AD%98%E4%B8%8B%E8%BD%BD%E5%9B%BE%E7%89%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d839e64a").then(next)
    },
  },
  {
    path: "/blog/web/canvas保存下载图片.html",
    redirect: "/blog/web/canvas%E4%BF%9D%E5%AD%98%E4%B8%8B%E8%BD%BD%E5%9B%BE%E7%89%87.html"
  },
  {
    name: "v-3307c5a5",
    path: "/blog/web/div%E5%AE%BD%E9%AB%98%E7%AD%89%E6%AF%94%E4%BE%8B%E8%87%AA%E9%80%82%E5%BA%94.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3307c5a5").then(next)
    },
  },
  {
    path: "/blog/web/div宽高等比例自适应.html",
    redirect: "/blog/web/div%E5%AE%BD%E9%AB%98%E7%AD%89%E6%AF%94%E4%BE%8B%E8%87%AA%E9%80%82%E5%BA%94.html"
  },
  {
    name: "v-6e6d6107",
    path: "/blog/web/js%20%E6%A8%A1%E5%9D%97%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e6d6107").then(next)
    },
  },
  {
    path: "/blog/web/js 模块导入导出.html",
    redirect: "/blog/web/js%20%E6%A8%A1%E5%9D%97%E5%AF%BC%E5%85%A5%E5%AF%BC%E5%87%BA.html"
  },
  {
    name: "v-01ad53cb",
    path: "/blog/web/js%20%E7%9F%A5%E8%AF%86%E7%82%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01ad53cb").then(next)
    },
  },
  {
    path: "/blog/web/js 知识点.html",
    redirect: "/blog/web/js%20%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    name: "v-64d37a69",
    path: "/blog/web/vue%E4%B8%AD%E4%BD%BF%E7%94%A8EChart.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-64d37a69").then(next)
    },
  },
  {
    path: "/blog/web/vue中使用EChart.html",
    redirect: "/blog/web/vue%E4%B8%AD%E4%BD%BF%E7%94%A8EChart.html"
  },
  {
    name: "v-a706545e",
    path: "/blog/web/vue%E7%BB%84%E4%BB%B6%E9%80%9A%E4%BF%A1%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a706545e").then(next)
    },
  },
  {
    path: "/blog/web/vue组件通信总结.html",
    redirect: "/blog/web/vue%E7%BB%84%E4%BB%B6%E9%80%9A%E4%BF%A1%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-7d8d473e",
    path: "/blog/web/vue%E8%B7%AF%E7%94%B1%E5%8A%A8%E7%94%BB%E5%92%8C%E7%BC%93%E5%AD%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7d8d473e").then(next)
    },
  },
  {
    path: "/blog/web/vue路由动画和缓存.html",
    redirect: "/blog/web/vue%E8%B7%AF%E7%94%B1%E5%8A%A8%E7%94%BB%E5%92%8C%E7%BC%93%E5%AD%98.html"
  },
  {
    name: "v-c392a398",
    path: "/blog/web/%E4%BC%98%E5%8C%96moment%E6%89%93%E5%8C%85.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c392a398").then(next)
    },
  },
  {
    path: "/blog/web/优化moment打包.html",
    redirect: "/blog/web/%E4%BC%98%E5%8C%96moment%E6%89%93%E5%8C%85.html"
  },
  {
    name: "v-10e6348e",
    path: "/blog/web/%E5%85%83%E7%B4%A0%E5%A4%A7%E5%B0%8F%E3%80%81%E4%BD%8D%E7%BD%AE%E3%80%81%E6%BB%9A%E5%8A%A8%E7%9B%B8%E5%85%B3%E7%9F%A5%E8%AF%86%E7%82%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10e6348e").then(next)
    },
  },
  {
    path: "/blog/web/元素大小、位置、滚动相关知识点.html",
    redirect: "/blog/web/%E5%85%83%E7%B4%A0%E5%A4%A7%E5%B0%8F%E3%80%81%E4%BD%8D%E7%BD%AE%E3%80%81%E6%BB%9A%E5%8A%A8%E7%9B%B8%E5%85%B3%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    name: "v-61a8155e",
    path: "/blog/web/%E5%85%A8%E5%B1%8F%E5%92%8C%E6%A8%AA%E7%AB%96%E5%B1%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61a8155e").then(next)
    },
  },
  {
    path: "/blog/web/全屏和横竖屏.html",
    redirect: "/blog/web/%E5%85%A8%E5%B1%8F%E5%92%8C%E6%A8%AA%E7%AB%96%E5%B1%8F.html"
  },
  {
    name: "v-6347c49c",
    path: "/blog/web/%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E6%B7%B1%E5%BA%A6%E5%85%8B%E9%9A%86%E9%9C%80%E8%A6%81%E7%9A%84%E7%9F%A5%E8%AF%86%E7%82%B9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6347c49c").then(next)
    },
  },
  {
    path: "/blog/web/实现一个深度克隆需要的知识点.html",
    redirect: "/blog/web/%E5%AE%9E%E7%8E%B0%E4%B8%80%E4%B8%AA%E6%B7%B1%E5%BA%A6%E5%85%8B%E9%9A%86%E9%9C%80%E8%A6%81%E7%9A%84%E7%9F%A5%E8%AF%86%E7%82%B9.html"
  },
  {
    name: "v-513d63d9",
    path: "/blog/web/%E5%BE%AA%E7%8E%AF%E3%80%81%E8%BF%AD%E4%BB%A3%E3%80%81%E5%B1%9E%E6%80%A7%E7%89%B9%E6%80%A7%E4%B8%8E%E5%B1%9E%E6%80%A7%E6%96%B9%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-513d63d9").then(next)
    },
  },
  {
    path: "/blog/web/循环、迭代、属性特性与属性方法.html",
    redirect: "/blog/web/%E5%BE%AA%E7%8E%AF%E3%80%81%E8%BF%AD%E4%BB%A3%E3%80%81%E5%B1%9E%E6%80%A7%E7%89%B9%E6%80%A7%E4%B8%8E%E5%B1%9E%E6%80%A7%E6%96%B9%E6%B3%95.html"
  },
  {
    name: "v-ae2807da",
    path: "/blog/web/%E6%80%BB%E7%BB%93%E8%87%AA%E5%B7%B1%E6%89%80%E9%81%87%E5%88%B0%E8%BF%87%E7%9A%84%E5%B8%83%E5%B1%80%E9%97%AE%E9%A2%98.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ae2807da").then(next)
    },
  },
  {
    path: "/blog/web/总结自己所遇到过的布局问题.html",
    redirect: "/blog/web/%E6%80%BB%E7%BB%93%E8%87%AA%E5%B7%B1%E6%89%80%E9%81%87%E5%88%B0%E8%BF%87%E7%9A%84%E5%B8%83%E5%B1%80%E9%97%AE%E9%A2%98.html"
  },
  {
    name: "v-e7cffb24",
    path: "/blog/web/%E6%8B%96%E6%8B%BD%E6%8E%92%E5%BA%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e7cffb24").then(next)
    },
  },
  {
    path: "/blog/web/拖拽排序.html",
    redirect: "/blog/web/%E6%8B%96%E6%8B%BD%E6%8E%92%E5%BA%8F.html"
  },
  {
    name: "v-65e02d6f",
    path: "/blog/web/%E6%96%87%E5%AD%97%E8%B5%B0%E9%A9%AC%E7%81%AF.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65e02d6f").then(next)
    },
  },
  {
    path: "/blog/web/文字走马灯.html",
    redirect: "/blog/web/%E6%96%87%E5%AD%97%E8%B5%B0%E9%A9%AC%E7%81%AF.html"
  },
  {
    name: "v-3b153825",
    path: "/blog/web/%E6%96%87%E5%AD%97%E8%B6%85%E5%87%BA%E7%9C%81%E7%95%A5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b153825").then(next)
    },
  },
  {
    path: "/blog/web/文字超出省略.html",
    redirect: "/blog/web/%E6%96%87%E5%AD%97%E8%B6%85%E5%87%BA%E7%9C%81%E7%95%A5.html"
  },
  {
    name: "v-73fdbc72",
    path: "/blog/web/%E6%B5%8F%E8%A7%88%E5%99%A8%E6%B8%B2%E6%9F%93%E4%BB%A5%E5%8F%8Acss%E3%80%81js%E9%98%BB%E5%A1%9E.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-73fdbc72").then(next)
    },
  },
  {
    path: "/blog/web/浏览器渲染以及css、js阻塞.html",
    redirect: "/blog/web/%E6%B5%8F%E8%A7%88%E5%99%A8%E6%B8%B2%E6%9F%93%E4%BB%A5%E5%8F%8Acss%E3%80%81js%E9%98%BB%E5%A1%9E.html"
  },
  {
    name: "v-48e86fc7",
    path: "/blog/web/%E6%BB%91%E5%8A%A8%E9%80%89%E6%8B%A9%E5%99%A8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48e86fc7").then(next)
    },
  },
  {
    path: "/blog/web/滑动选择器.html",
    redirect: "/blog/web/%E6%BB%91%E5%8A%A8%E9%80%89%E6%8B%A9%E5%99%A8.html"
  },
  {
    name: "v-82555ff0",
    path: "/blog/web/%E7%9B%91%E5%90%ACdom%E7%9A%84%E5%8F%98%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82555ff0").then(next)
    },
  },
  {
    path: "/blog/web/监听dom的变化.html",
    redirect: "/blog/web/%E7%9B%91%E5%90%ACdom%E7%9A%84%E5%8F%98%E5%8C%96.html"
  },
  {
    name: "v-16c4aa7d",
    path: "/blog/web/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E5%AD%A6%E4%B9%A0%E4%B8%8E%E6%80%BB%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16c4aa7d").then(next)
    },
  },
  {
    path: "/blog/web/移动端适配学习与总结.html",
    redirect: "/blog/web/%E7%A7%BB%E5%8A%A8%E7%AB%AF%E9%80%82%E9%85%8D%E5%AD%A6%E4%B9%A0%E4%B8%8E%E6%80%BB%E7%BB%93.html"
  },
  {
    name: "v-57b46da2",
    path: "/blog/web/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57b46da2").then(next)
    },
  },
  {
    path: "/blog/web/自定义事件.html",
    redirect: "/blog/web/%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BA%8B%E4%BB%B6.html"
  },
  {
    name: "v-26a3239e",
    path: "/blog/web/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8D%95%E9%80%89%E6%A1%86%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26a3239e").then(next)
    },
  },
  {
    path: "/blog/web/自定义单选框组件.html",
    redirect: "/blog/web/%E8%87%AA%E5%AE%9A%E4%B9%89%E5%8D%95%E9%80%89%E6%A1%86%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-3fe3907f",
    path: "/blog/web/%E8%99%9A%E6%8B%9Fdom%E5%92%8C%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3fe3907f").then(next)
    },
  },
  {
    path: "/blog/web/虚拟dom和组件.html",
    redirect: "/blog/web/%E8%99%9A%E6%8B%9Fdom%E5%92%8C%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-36e64d02",
    path: "/blog/web/%E9%80%8F%E6%98%8E%E6%80%A7%E7%BB%84%E4%BB%B6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-36e64d02").then(next)
    },
  },
  {
    path: "/blog/web/透明性组件.html",
    redirect: "/blog/web/%E9%80%8F%E6%98%8E%E6%80%A7%E7%BB%84%E4%BB%B6.html"
  },
  {
    name: "v-7e5ff7fd",
    path: "/doc/canvas%E4%BF%9D%E5%AD%98%E4%B8%8B%E8%BD%BD%E5%9B%BE%E7%89%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e5ff7fd").then(next)
    },
  },
  {
    path: "/doc/canvas保存下载图片.html",
    redirect: "/doc/canvas%E4%BF%9D%E5%AD%98%E4%B8%8B%E8%BD%BD%E5%9B%BE%E7%89%87.html"
  },
  {
    name: "v-0123048a",
    path: "/doc/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0123048a").then(next)
    },
  },
  {
    path: "/doc/index.html",
    redirect: "/doc/"
  },
  {
    name: "v-1ed23a52",
    path: "/tag/0/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ed23a52").then(next)
    },
  },
  {
    path: "/tag/0/index.html",
    redirect: "/tag/0/"
  },
  {
    name: "v-3937c6e0",
    path: "/tag/1/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3937c6e0").then(next)
    },
  },
  {
    path: "/tag/1/index.html",
    redirect: "/tag/1/"
  },
  {
    name: "v-b0140264",
    path: "/tag/2/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b0140264").then(next)
    },
  },
  {
    path: "/tag/2/index.html",
    redirect: "/tag/2/"
  },
  {
    name: "v-6c87e10c",
    path: "/tag/3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c87e10c").then(next)
    },
  },
  {
    path: "/tag/3/index.html",
    redirect: "/tag/3/"
  },
  {
    name: "v-3119c34a",
    path: "/tag/4/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3119c34a").then(next)
    },
  },
  {
    path: "/tag/4/index.html",
    redirect: "/tag/4/"
  },
  {
    name: "v-14a8b4f0",
    path: "/tag/5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14a8b4f0").then(next)
    },
  },
  {
    path: "/tag/5/index.html",
    redirect: "/tag/5/"
  },
  {
    name: "v-8b84f074",
    path: "/tag/6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8b84f074").then(next)
    },
  },
  {
    path: "/tag/6/index.html",
    redirect: "/tag/6/"
  },
  {
    name: "v-7ecf6a04",
    path: "/tag/7/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ecf6a04").then(next)
    },
  },
  {
    path: "/tag/7/index.html",
    redirect: "/tag/7/"
  },
  {
    name: "v-43614c42",
    path: "/tag/8/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43614c42").then(next)
    },
  },
  {
    path: "/tag/8/index.html",
    redirect: "/tag/8/"
  },
  {
    name: "v-07f32e80",
    path: "/tag/9/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07f32e80").then(next)
    },
  },
  {
    path: "/tag/9/index.html",
    redirect: "/tag/9/"
  },
  {
    name: "v-8c9d11d8",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8c9d11d8").then(next)
    },
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-223ae75a",
    path: "/tool/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-223ae75a").then(next)
    },
  },
  {
    path: "/tool/index.html",
    redirect: "/tool/"
  },
  {
    name: "v-3b92a8c0",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3b92a8c0").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]